### ISSUE TITLE
Error while building project

### ISSUE THREAD

**Issue by serhiitereshchenko** [antest1/KcaSniffer#1]
I can't build the project correctly. When I export all headers for project I get next error:

> In file included from /home/serg/AndroidStudioProjects/KcaSniffer/app/src/main/jni/netguard/netguard.c:20:
> In file included from /home/serg/AndroidStudioProjects/KcaSniffer/app/src/main/jni/netguard/netguard.h:7:
> /usr/include/pthread.h:681:6: error: 'regparm' is not valid on this platform
>      __cleanup_fct_attribute;
>      ^~~~~~~~~~~~~~~~~~~~~~~
> /usr/include/bits/pthreadtypes.h:255:50: note: expanded from macro '__cleanup_fct_attribute'
> # define __cleanup_fct_attribute __attribute__ ((__regparm__ (1)))

Could anyone help me please?

**Comment by antest1** [comment]
This problem may related with this link:
- https://stackoverflow.com/questions/37812531/i-ran-into-this-error-message-regparm-is-not-valid-on-this-platform
- https://github.com/pocoproject/poco/issues/1350

It seems to be rather compiler/setting problem, as I don't have any issue with this. (I'm using android studio 3.0.1 in Windows) Make sure that you have the latest CMake and NDK.

※ As I'll update some build-related files, it would be better to try again after the new commit (I'm not sure this would solve the issue...)

**Comment by SsIDit** [comment]
Thank you very much, I solved my problem. It was related to invalid compiler. But now I have other kind of problem. My java code can't see native jni methods:

```
    private native void jni_init();

    private native void jni_start(int tun, boolean fwd53, int rcode, int loglevel);

    private native void jni_stop(int tun, boolean clr);

    private native int jni_get_mtu();

    private native void jni_socks5(String addr, int port, String username, String password);

    private native void jni_done();
```
Application crashes when each of them is called from app.

**Comment by serhiitereshchenko** [comment]
Thank you very much. I solved my problem. The problem was because of invalid compiler files.

**Comment by antest1** [comment]
Good :)

As the problem was solved, I'll close the issue.
